version: '3.8'

services:

  test:
    container_name: test
    ports:
      - "8006:80" 
    environment:
      - BIANXIE_BASE=https://api.bianxieai.com/v1
      - BIANXIE_API_KEY=sk-lN2p72K5p8H32XQV5l1NdIWqrrjNWqRkFs0xETUtqeNvDw26

    restart: always 
networks:
  webnet:
    driver: bridge
